public class EnrichLeadController {
    
  /*  public static void enrichcallout(String leadID){
        
        try{
            Lead ld = [SELECT Id, Policy_Type__c,Year_Built__c, Stories__c,Roof_Type__c,Square_Footage__c,Dwelling_Type__c, Vehicle_Vin__c, Vehicle_Make__c, Vehicle_Model__c, 
                                    Vehicle_Year__c, Street,City,State,PostalCode,County__c
                                    FROM Lead 
                                    WHERE Id =: leadID];
            
            /*if(ld.Policy_Type__c== 'Auto'){
                requestAutoEnrichment(ld);
            }*/
           /* if(ld.Policy_Type__c == 'Home'){
                requestHomeEnrichment(ld);
            }*/
         
      //  } catch(exception exec){
      //      System.debug('-- errors: ' + exec.getMessage());
      //      throw new AuraException(exec.getMessage());
     //   }
 //   }*/
    
    
    
    
     
}